### PR TITLE
Allow embedding of PDF, video, etc. using image links

### LINKED ISSUE #350: Support embedding PDF using regular Markdown syntax
ie., `` should also embed the PDF file like it does for images.

[This change](https://github.com/EmaApps/emanote/pull/341/commits/fd885e7eca81d81fb017eb24cd90cb095574785d) (made in #341, but reverted) functionally achieves it, but we want to do it in a simpler manner without overloading `Heist.Extra` with emanote-specific functions. `Heist.Extra` will eventually be made a library of its own; thus, it should not contain code specific to Emanote templates.

### PR DESCRIPTION
**Pull request by srid**
Resolves #350

FYI @mnaoumov https://github.com/EmaApps/emanote/pull/341#issuecomment-1250157729 - this is how it should be done.

### CODE REVIEW

**Comment by srid** [comment]
Doing it this way means this syntax will also work for other formats, like video formats:

```markdown
![](foo.mp4)
```

**Comment by mnaoumov** [comment]
@srid Maybe `Emanote.Pandoc.Link.InlineImage` name has to be changed then? Don't you think it is confusing now?

**Comment by mnaoumov** [comment]
@srid maybe `InlineStaticFile` would be better ?

**Comment by srid** [comment]
`InlineRef`, defined under `Emanote.Pandoc`, knows nothing about non-Pandoc specific types (like `StaticFile`). So I'd say it is fine as is. The type exists simply to distinguish between the two possible inline links allowed by Pandoc AST.

**Comment by srid** [comment]
I actually should refactor the whole pandoc related rendering code one day. It has gotten way too complex. Meanwhile, I decoupled the Heist utilities to https://github.com/srid/heist-extra

**Comment by mnaoumov** [comment]
@srid I understand that Pandoc mistakenly calls everything `Image` but I guess your should not keep using that leaking abstraction further in your library. What if you rename it to `InlineResource` and maybe write in the comment that Pandoc mistakenly calls `Text.Pandoc.Definition.Image` all resources including images, videos, pdfs etc? This will make your library's API clearer and leaked abstractions from Pandoc will be encapsulated within `Emanote.Pandoc.Link` module

**Comment by srid** [comment]
> Pandoc mistakenly calls `Text.Pandoc.Definition.Image` all resources including images, videos, pdfs etc?

Pandoc is behaving correctly. Per commonmark spec, `` can only be used for images. 

https://commonmark.org/help/tutorial/08-images.html

It just so happens that Obsidian and the like decide to overload this syntax for embedding non-image resources.

If we want to improve the API properly, perhaps we should start from Pandoc itself (as its AST is not that flexible currently); eg.: https://github.com/jgm/pandoc-types/issues/98

**Comment by mnaoumov** [comment]
@srid ok, I take my words back about misbehaving Pandoc. I'm so used to the embedded videos, audios, pdfs, so I forgot that pure Markdown still doesn't allow it

**Pull request merged**
