### PR TITLE
nix: Update all inputs

### PR DESCRIPTION
**Pull request by srid**

### CODE REVIEW

**Comment by srid** [comment]
Same build failure on macOS as #557

**Comment by srid** [comment]
```
error: output '/nix/store/1i44wa0v4lwagr0b43sd0z2rj9prn926-emanote-source-1.3.18.1' is not allowed to refer to the following paths:
         /nix/store/4jffra4rajjhpb4ihlnhm3njnzskzrnc-ghc-9.6.6
error: 1 dependencies of derivation '/nix/store/bfkn8m2ig9gw77ccsgakz319zz8lkaj8-emanote-1.3.18.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fn2m0ianck5c1x0yj6ralz8lavnya0qg-devour-output.json.drv' failed to build
```

`justStaticExecutables` is the issue

> `justStaticExecutables` is practically useless since GHC is pulled in transitively.

https://github.com/NixOS/nixpkgs/issues/318013

**Comment by srid** [comment]
Using the improved Nix from @roberth 's PR https://github.com/NixOS/nix/pull/10877

```
❯ nix run github:hercules-ci/nix/report-forbidden-path-as-chain build
...
error: output '/nix/store/1i44wa0v4lwagr0b43sd0z2rj9prn926-emanote-source-1.3.18.1' is not allowed to refer to the following paths:
         /nix/store/4jffra4rajjhpb4ihlnhm3njnzskzrnc-ghc-9.6.6
error: 1 dependencies of derivation '/nix/store/bfkn8m2ig9gw77ccsgakz319zz8lkaj8-emanote-1.3.18.1.drv' failed to build
```

Hmm, that doesn't behave like the PR description says it would? @roberth Any ideas?

**Comment by srid** [comment]
Undoing #392 (https://github.com/srid/emanote/issues/295) for macOS to get this PR merged. Somebody else can fix this upstream and/or here.

**Comment by roberth** [comment]
> [NixOS/nix#10877](https://github.com/NixOS/nix/pull/10877)

It was probably built by your system's nix daemon instead. You could use `--store ~/tmp-store` on NixOS, or install the PR system-wide otherwise, or run it with sudo.

**Pull request merged**
