### PR TITLE
Update tristan's website link

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
I've changed the domain name and linked to a page that explain why emanote is the best :)

**Comment by srid** [comment]
> linked to a page that explain why emanote is the best :)

Cool :-)

https://midirus.com/website

**Comment by srid** [comment]
> I am tempted to use something more simple like [matklad.github.io](https://github.com/matklad/matklad.github.io/tree/master/src). But this would be a lot of work, and I’m happy to contribute to a general purpose system like [emanote](https://emanote.srid.ca/).

That site renders like a blog: https://matklad.github.io/

Incidentally, I've been looking to start a blog myself ... Emanote needs to be improve in various ways to also act as a good blogging system.

Also, I've been meaning to refactor the codebase significantly, since I feel it has become complex to make changes.

**Comment by TristanCacqueray** [comment]
I meant emanote is not that complex, for what it does it's actually impressive. Though I wouldn't mind a simpler codebase, but I'm not sure that's worth the effort.

What do you think is missing for a good blogging system?

**Pull request merged**
