### PR TITLE
Resolve ambiguities based on closer common ancestor

### PR DESCRIPTION
**Pull request by srid**
- [x] Prototype
- [ ] Do the reverse: 
  - [x] "backlinks" should not show all the places linking to `[[foo]]` (if that foo was an ambiguity resolved)
  - [ ] what about uptree? folgezettel parents, etc.
- [x] refactor

### CODE REVIEW

**Comment by edrex** [comment]
I was just looking into how it might be possible to add resolution (nearest ancestor), since I have same-name notes in different directories all over the place, making the current behavior a blocker for using emanote for my big repo. So great to see a patch in progress Srid!

I would prefer that the behavior be to omit descendant search entirely, and search only ancestors (that's what Ikiwiki does), but I don't need that to get unblocked.

I just did a test build and it's still showing ambiguous link errors for me:

Screenshot-2024-01-18-12:56

(out of scope here, the rendering for these inline errors has always seemed broken for me. Missing style or something?)

LMK if you want review when you're ready.

**Comment by edrex** [comment]
Previous discussion, starting at https://github.com/srid/emanote/discussions/115#discussioncomment-1149833

**Comment by srid** [comment]
> I would prefer that the behavior be to omit descendant search entirely, and search only ancestors (that's what Ikiwiki does), but I don't need that to get unblocked.

Without descendant search, it would not be possible to "combine" multiple sites though (see #494), and thus it would break https://community.flake.parts/ (the various docs come from different repos; and `guide.md` for example exists in both haskell-flake and nixos-flake repos).

**Comment by edrex** [comment]
I was too ambigious with "... omit descendant search entirely". I meant a ref `Foo` shouldn't resolve to `/A/Foo.md`, but (`A/Foo`) still would. So a ref R from path A would resolve to B if and only if `B = Apre + Ref` for some Apre in Prefixes(A).

This would require all descending path elements to be explicit in refs. This would allow matching on subdirs for flexible reference remapping (eg, a local site registry mapping ref prefixes to URL prefixes for external sites).

I'm only guessing at the use-case you're working on. Am I missing part of the requirement?

**Comment by srid** [comment]
@edrex What is the value of `Prefixes(A)` if A = `/Foo/Bar/Qux.md`? 

If `Prefixes` == `["/", "/Foo", "/Foo/Bar"]`, then by the rule you stated above, Qux.md can link to **any** note in the notebook. 

Could you provide a more rigorous logic so I can understand what you are proposing?

**Comment by srid** [comment]
I'm gonna merge this now; but will always be happy to revisit the ambiguity resolution algorithm based on convincing rationale.

**Pull request merged**
