### PR TITLE
Support --override-index-data argument

### LINKED ISSUE #20: Allow overriding base URL in CLI
Emanote's default template hardcodes `<base href="/">` via reading the "/" from `index.yaml` (`templates.baseUrl: /`). The default works in live server. But its value differs in certain deployment environments, like GitHub Pages. We should provide a way to override this when generating the static HTML (i.e., outside of live server).

```sh
emanote --override-index-data='{"template": {"baseUrl": "srid.github.io/mynotes"} }' gen
```

Note that this command itself is general, and allows overriding anything in the "index data" (which currently is represented by the top-level `index.yaml`). We can leverage the existing `Data.Aeson.Extra.Merge` to do this.

Goal: continue to use `/` as baseUrl in live server mode, but something else during deployment.

### PR DESCRIPTION
**Pull request by hi-learn-triz-and-usit**
Fixes #20

### CODE REVIEW

**Comment by hi-learn-triz-and-usit** [comment]
New help looks like this
```
Emanote

Usage: emanote [--override-index-data JSON] [-C PATH] [COMMAND]
  Emanote - A spiritual successor to Neuron

Available options:
  --override-index-data JSON
                           Override the default parameters in index.yaml. For
                           example, to set the baseUrl, use {"template":
                           {"baseUrl": URL}}.
  -C PATH                  Run as if ema was started in PATH instead of the
                           current working directory.
  -h,--help                Show this help text

Available commands:
  gen                      Generate static HTML files
```

**Comment by hi-learn-triz-and-usit** [comment]
The actual functionality is not yet hooked up.

**Comment by hi-learn-triz-and-usit** [comment]
With #20 closed, what do you want done to support #35

**Comment by srid** [comment]
Implementations details in https://github.com/srid/emanote/issues/20#issuecomment-848819699 - but the comment below has an open question; I haven't had any chance to think about that yet, unless you already have ideas on that.

**Comment by hi-learn-triz-and-usit** [comment]
It seems like I won't have time to work on even this simple issue 😞 . Oh, well. Closing so as not to prevent others from taking it over.

**Pull request closed without merging**
