### PR TITLE
Fix H2 styling & Add documentation

### PR DESCRIPTION
**Pull request by bolt12**
See https://github.com/srid/emanote/discussions/438

I fix the styling on H2 heading component and attempt to add a section about how to override default styling.

### CODE REVIEW

**Review by srid — APPROVED** [review]
Great, thanks.

**Comment by bolt12** [comment]
My pleasure!

**Comment by kukimik** [comment]
I'm a bit late, but this already was described, at least in part, here: http://emanote.srid.ca/guide/html-template.

I believe there should at least be a hyperlink between the two descriptions.

**Comment by srid** [comment]
> I'm a bit late, but this already was described, at least in part, here: http://emanote.srid.ca/guide/html-template.
> 
> I believe there should at least be a hyperlink between the two descriptions.

I feel like we should just move it to the HTML template page.

**Pull request merged**
